export interface ClaudeMdData {
  name: string;
  email: string;
  role: string;
  company: string;
}

export function generateClaudeMd(data: ClaudeMdData): string {
  const { name, email, role, company } = data;
  return [
    '# CLAUDE.md',
    '',
    '> This file provides context about the vault owner to Claude Code.',
    '> Generated by `tmr init` — edit freely to add more detail.',
    '',
    '## Identity',
    '',
    `- **Name:** ${name}`,
    `- **Email:** ${email}`,
    `- **Role:** ${role}`,
    `- **Company:** ${company}`,
    '',
    '## Vault Structure',
    '',
    '| Folder | Purpose |',
    '|--------|---------|',
    '| `inbox/` | Drop meeting notes, documents, and items to process |',
    '| `archive/` | Processed files moved by `tmr process` |',
    '| `config/` | System configuration |',
    '| `my-career/` | Career development (assessments, feedbacks, PDP) |',
    '| `my-company/` | Company context: members, meetings, projects |',
    '| `my-leadership/` | Leadership principles and frameworks |',
    '| `my-tasks/` | Task tracking: tasks.md, today.md, this-week.md, this-month.md, this-quarter.md |',
    '| `my-teams/` | Team members, team definitions, feedback templates |',
    '| `knowledge-base/` | Company knowledge: branding, people, process, security |',
    '',
    '## Communication Style',
    '',
    '<!-- Fill in your preferences to help Claude understand your style -->',
    '',
    '**Preferred tone:** [Direct / Collaborative / Formal / Informal]',
    '**Meeting preferences:** [Async-first / Sync when needed]',
    '**Feedback approach:** [Real-time / Written / Structured]',
    '',
    '## Company & Team Context',
    '',
    'See `my-company/` for company and organizational context.',
    'See `my-teams/` for team member profiles.',
    '',
  ].join('\n');
}
