import path from 'node:path';
import { homedir } from 'node:os';
import matter from 'gray-matter';
import { FileSystemService, fileSystemService } from './file-system.service.js';
import { LeadershipService, leadershipService } from './leadership.service.js';
import { TeamService, teamService } from './team.service.js';

// ── Vault directory list ──────────────────────────────────────────────────────

const VAULT_DIRS = [
  'inbox',
  'archive',
  'my-tasks',
  'my-teams/members',
  'my-teams/teams',
  'my-company/members',
  'my-company/projects',
  'my-leadership',
  'my-career',
  'knowledge-base',
  '.claude/skills',
  '.cursor/rules/tmr',
] as const;

// ── CLAUDE.md stub ────────────────────────────────────────────────────────────

function buildClaudeMdStub(): string {
  return [
    '# CLAUDE.md',
    '',
    '> This file provides context about the vault owner to Claude Code.',
    '> Generated by `tmr init` — edit freely to add more detail.',
    '',
    '## Identity',
    '',
    '- **Name:** (set during init)',
    '- **Email:** (set during init)',
    '- **Role:** (set during init)',
    '- **Company:** (set during init)',
    '',
    '## Vault Structure',
    '',
    '| Folder | Purpose |',
    '|--------|---------|',
    '| `inbox/` | Drop meeting notes, documents, and items to process |',
    '| `archive/` | Processed files moved by `tmr process` |',
    '| `my-career/` | Career development (assessments, feedbacks, PDP) |',
    '| `my-company/` | Company context: members, meetings, projects |',
    '| `my-leadership/` | Leadership principles and frameworks |',
    '| `my-tasks/` | Task tracking: tasks.md, today.md, this-week.md, this-month.md, this-quarter.md |',
    '| `my-teams/` | Team members, team definitions |',
    '| `knowledge-base/` | Company knowledge: branding, people, process, security |',
    '',
    '## Communication Style',
    '',
    '<!-- Fill in your preferences to help Claude understand your style -->',
    '',
    '**Preferred tone:** [Direct / Collaborative / Formal / Informal]',
    '**Meeting preferences:** [Async-first / Sync when needed]',
    '**Feedback approach:** [Real-time / Written / Structured]',
    '',
  ].join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function todayIso(): string {
  return new Date().toISOString().split('T')[0] as string;
}

// ── InitService ───────────────────────────────────────────────────────────────

export class InitService {
  constructor(
    private readonly _fs: FileSystemService,
    private readonly _leadership: LeadershipService,
    private readonly _team: TeamService,
  ) {}

  /**
   * Resolves a raw vault path input to an absolute path.
   * - Empty or whitespace-only → `process.cwd()`
   * - `~/...` prefix → expanded to OS home directory
   * - Any other value → returned as-is
   */
  resolveVaultPath(input: string): string {
    const trimmed = input.trim();
    if (!trimmed) return process.cwd();
    if (trimmed === '~') return homedir();
    if (trimmed.startsWith('~/')) return path.join(homedir(), trimmed.slice(2));
    return trimmed;
  }

  /**
   * Creates the standard vault directory structure and writes a CLAUDE.md stub.
   * Exactly 12 directories are created — no more, no less.
   * Throws on any file system failure; the caller is responsible for surfacing
   * the error to the user.
   *
   * @throws if any directory or file creation fails
   */
  async scaffold(vaultPath: string): Promise<void> {
    await Promise.all(VAULT_DIRS.map((dir) => this._fs.createDirectory(path.join(vaultPath, dir))));
    await this._fs.writeFile(path.join(vaultPath, 'CLAUDE.md'), buildClaudeMdStub());
  }

  /**
   * Writes the user's own career profile to `my-career/<email>/<email>.md`.
   * Creates the parent directory if it does not yet exist.
   * Throws on any file system failure.
   */
  async writeUserProfile(
    vaultPath: string,
    opts: { email: string; name: string; role: string },
  ): Promise<void> {
    const email = opts.email.trim().toLowerCase();
    const dir = path.join(vaultPath, 'my-career', email);
    const filePath = path.join(dir, `${email}.md`);
    const fm = { email, name: opts.name, role: opts.role, date_added: todayIso() };
    const content = matter.stringify('\n# Career Profile\n\n## Notes\n\n## Goals\n', fm);
    await this._fs.createDirectory(dir);
    await this._fs.writeFile(filePath, content);
  }

  /**
   * Creates a leadership profile for the user's direct leader.
   * Delegates to `LeadershipService.addLeadership()` which writes
   * `my-leadership/<email>/<email>.md` and creates a `1on1s/` subdirectory.
   * Throws on any file system failure.
   */
  async writeLeaderProfile(
    vaultPath: string,
    opts: { email: string; name: string; role: string },
  ): Promise<void> {
    await this._leadership.addLeadership(
      opts.email,
      { name: opts.name, role: opts.role },
      vaultPath,
    );
  }

  /**
   * Creates team folder entries for each supplied team name.
   * Delegates to `TeamService.createTeam()` which normalises the name via
   * `normalizeSlug()` internally — do NOT pre-normalise here.
   * Teams are created sequentially to avoid interleaved directory creation.
   * Throws on any file system failure.
   */
  async createTeams(vaultPath: string, teamNames: string[]): Promise<void> {
    for (const name of teamNames) {
      await this._team.createTeam(name, vaultPath);
    }
  }
}

export const initService = new InitService(fileSystemService, leadershipService, teamService);
