import path from 'node:path';
import { homedir } from 'node:os';
import { FileSystemService, fileSystemService } from './file-system.service.js';

// ── Vault directory list ──────────────────────────────────────────────────────

const VAULT_DIRS = [
  'inbox',
  'archive',
  'my-tasks',
  'my-teams/members',
  'my-teams/teams',
  'my-company/members',
  'my-company/projects',
  'my-leadership',
  'my-career',
  'knowledge-base',
  '.claude/skills',
  '.cursor/rules/tmr',
] as const;

// ── CLAUDE.md stub ────────────────────────────────────────────────────────────

function buildClaudeMdStub(): string {
  return [
    '# CLAUDE.md',
    '',
    '> This file provides context about the vault owner to Claude Code.',
    '> Generated by `tmr init` — edit freely to add more detail.',
    '',
    '## Identity',
    '',
    '- **Name:** (set during init)',
    '- **Email:** (set during init)',
    '- **Role:** (set during init)',
    '- **Company:** (set during init)',
    '',
    '## Vault Structure',
    '',
    '| Folder | Purpose |',
    '|--------|---------|',
    '| `inbox/` | Drop meeting notes, documents, and items to process |',
    '| `archive/` | Processed files moved by `tmr process` |',
    '| `my-career/` | Career development (assessments, feedbacks, PDP) |',
    '| `my-company/` | Company context: members, meetings, projects |',
    '| `my-leadership/` | Leadership principles and frameworks |',
    '| `my-tasks/` | Task tracking: tasks.md, today.md, this-week.md, this-month.md, this-quarter.md |',
    '| `my-teams/` | Team members, team definitions |',
    '| `knowledge-base/` | Company knowledge: branding, people, process, security |',
    '',
    '## Communication Style',
    '',
    '<!-- Fill in your preferences to help Claude understand your style -->',
    '',
    '**Preferred tone:** [Direct / Collaborative / Formal / Informal]',
    '**Meeting preferences:** [Async-first / Sync when needed]',
    '**Feedback approach:** [Real-time / Written / Structured]',
    '',
  ].join('\n');
}

// ── InitService ───────────────────────────────────────────────────────────────

export class InitService {
  constructor(private readonly _fs: FileSystemService) {}

  /**
   * Resolves a raw vault path input to an absolute path.
   * - Empty or whitespace-only → `process.cwd()`
   * - `~/...` prefix → expanded to OS home directory
   * - Any other value → returned as-is
   */
  resolveVaultPath(input: string): string {
    const trimmed = input.trim();
    if (!trimmed) return process.cwd();
    if (trimmed === '~') return homedir();
    if (trimmed.startsWith('~/')) return path.join(homedir(), trimmed.slice(2));
    return trimmed;
  }

  /**
   * Creates the standard vault directory structure and writes a CLAUDE.md stub.
   * Exactly 12 directories are created — no more, no less.
   * Throws on any file system failure; the caller is responsible for surfacing
   * the error to the user.
   *
   * @throws if any directory or file creation fails
   */
  async scaffold(vaultPath: string): Promise<void> {
    await Promise.all(VAULT_DIRS.map((dir) => this._fs.createDirectory(path.join(vaultPath, dir))));
    await this._fs.writeFile(path.join(vaultPath, 'CLAUDE.md'), buildClaudeMdStub());
  }
}

export const initService = new InitService(fileSystemService);
