import * as fs from 'node:fs';
import path from 'node:path';
import { homedir } from 'node:os';
import { fileURLToPath } from 'node:url';
import matter from 'gray-matter';
import { FileSystemService, fileSystemService } from './file-system.service.js';
import { LeadershipService, leadershipService } from './leadership.service.js';
import { TeamService, teamService } from './team.service.js';
import { SkillRegistryService } from './skill-registry.service.js';
import { logger } from '../utils/logger.js';
import { printSuccess, printInfo } from '../utils/display.js';
import { INBOX_SAMPLE_FILES, generateVaultReadme } from '../templates/onboarding.templates.js';
import { formatWikiLink } from '../utils/wiki-link.js';

// ── Vault directory list ──────────────────────────────────────────────────────

const VAULT_DIRS = [
  'inbox',
  'archive',
  'my-tasks',
  'my-teams/members',
  'my-teams/teams',
  'my-company/members',
  'my-company/contractors',
  'my-company/projects',
  'my-leadership',
  'my-career',
  'my-career/performance-reviews',
  'knowledge-base',
  'config',
  '.claude/skills',
  '.cursor/rules/tmr',
] as const;

// ── CLAUDE.md stub ────────────────────────────────────────────────────────────

function buildClaudeMdStub(): string {
  return [
    '# CLAUDE.md',
    '',
    '> This file provides context about the vault owner to Claude Code.',
    '> Generated by `tmr init` — edit freely to add more detail.',
    '',
    '## Identity',
    '',
    '- **Name:** (set during init)',
    '- **Email:** (set during init)',
    '- **Role:** (set during init)',
    '- **Company:** (set during init)',
    '',
    '## Vault Structure',
    '',
    '| Folder | Purpose |',
    '|--------|---------|',
    '| `inbox/` | Drop meeting notes, documents, and items to process |',
    '| `archive/` | Processed files moved by `tmr process` |',
    '| `my-career/` | Career development (assessments, feedbacks, PDP) |',
    '| `my-company/` | Company context: members, meetings, projects |',
    '| `my-leadership/` | Leadership principles and frameworks |',
    '| `my-tasks/` | Task tracking: tasks.md, today.md, this-week.md, this-month.md, this-quarter.md |',
    '| `my-teams/` | Team members, team definitions |',
    '| `knowledge-base/` | Company knowledge: branding, people, process, security |',
    '',
    '## Communication Style',
    '',
    '<!-- Fill in your preferences to help Claude understand your style -->',
    '',
    '**Preferred tone:** [Direct / Collaborative / Formal / Informal]',
    '**Meeting preferences:** [Async-first / Sync when needed]',
    '**Feedback approach:** [Real-time / Written / Structured]',
    '',
  ].join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function parseBundledVersion(content: string): string {
  const match = /<!--\s*version:\s*(\S+)\s*-->/.exec(content);
  return match?.[1] ?? '0.0.0';
}

function todayIso(): string {
  return new Date().toISOString().split('T')[0] as string;
}

// ── InitService ───────────────────────────────────────────────────────────────

export class InitService {
  constructor(
    private readonly _fs: FileSystemService,
    private readonly _leadership: LeadershipService,
    private readonly _team: TeamService,
    private readonly _skillRegistryFactory: (workspaceRoot: string) => SkillRegistryService = (
      wr,
    ) => new SkillRegistryService(wr),
    private readonly _readSkillFile: (filePath: string) => string = (p) =>
      fs.readFileSync(p, 'utf8'),
  ) {}

  /**
   * Resolves a raw vault path input to an absolute path.
   * - Empty or whitespace-only → `process.cwd()`
   * - `~/...` prefix → expanded to OS home directory
   * - Any other value → returned as-is
   */
  resolveVaultPath(input: string): string {
    const trimmed = input.trim();
    if (!trimmed) return process.cwd();
    if (trimmed === '~') return homedir();
    if (trimmed.startsWith('~/')) return path.join(homedir(), trimmed.slice(2));
    return trimmed;
  }

  /**
   * Creates the standard vault directory structure and writes a CLAUDE.md stub.
   * Exactly 14 directories are created — no more, no less.
   * Throws on any file system failure; the caller is responsible for surfacing
   * the error to the user.
   *
   * @throws if any directory or file creation fails
   */
  async scaffold(vaultPath: string): Promise<void> {
    await Promise.all(VAULT_DIRS.map((dir) => this._fs.createDirectory(path.join(vaultPath, dir))));
    await this._fs.writeFile(path.join(vaultPath, 'CLAUDE.md'), buildClaudeMdStub());
    await this.writeSentinel(vaultPath);
  }

  /**
   * Writes the .tmr sentinel file at the vault root.
   * Makes the vault self-identifying — `getWorkspaceRoot()` walks up from cwd
   * until it finds this file.
   */
  async writeSentinel(vaultPath: string): Promise<void> {
    const content = JSON.stringify({ version: '1.0.0', created: todayIso() }, null, 2);
    await this._fs.writeFile(path.join(vaultPath, '.tmr'), content);
  }

  /**
   * Walks up the directory tree from `fromDir` looking for a `.tmr` sentinel file.
   * Returns the vault root path if found, null otherwise.
   * Synchronous — mirrors `getWorkspaceRoot()` walk-up logic.
   */
  findExistingVault(fromDir: string): string | null {
    let dir = fromDir;
    while (true) {
      if (fs.existsSync(path.join(dir, '.tmr'))) return dir;
      const parent = path.dirname(dir);
      if (parent === dir) break; // reached filesystem root
      dir = parent;
    }
    return null;
  }

  /**
   * Writes the user's own career profile to `my-career/<email>.md` (flat — no subdirectory).
   * `my-career/` is guaranteed to exist after `scaffold()`, so no directory creation is needed.
   * Throws on any file system failure.
   */
  async writeUserProfile(
    vaultPath: string,
    opts: { email: string; name: string; role: string; leaderEmail?: string },
  ): Promise<void> {
    const email = opts.email.trim().toLowerCase();
    const filePath = path.join(vaultPath, 'my-career', `${email}.md`);
    const fm = {
      email,
      name: opts.name,
      role: opts.role,
      relationship: 'self',
      date_added: todayIso(),
    };

    let body = '\n# Career Profile\n\n## Notes\n\n## Goals\n';

    if (opts.leaderEmail?.trim()) {
      const leaderEmail = opts.leaderEmail.trim().toLowerCase();
      const leaderFile = path.join(vaultPath, 'my-leadership', leaderEmail, `${leaderEmail}.md`);
      const leaderLink = formatWikiLink(leaderFile, filePath, leaderEmail);
      body += `\n## Leadership\n\n- ${leaderLink}\n`;
    }

    const content = matter.stringify(body, fm);
    await this._fs.writeFile(filePath, content);
  }

  /**
   * Creates a leadership profile for the user's direct leader.
   * Delegates to `LeadershipService.addLeadership()` which writes
   * `my-leadership/<email>/<email>.md` and creates a `1on1s/` subdirectory.
   * Throws on any file system failure.
   */
  async writeLeaderProfile(
    vaultPath: string,
    opts: { email: string; name: string; role: string; location?: string },
  ): Promise<void> {
    await this._leadership.addLeadership(
      opts.email,
      { name: opts.name, role: opts.role, location: opts.location },
      vaultPath,
    );
  }

  /**
   * Creates team folder entries for each supplied team name.
   * Delegates to `TeamService.createTeam()` which normalises the name via
   * `normalizeSlug()` internally — do NOT pre-normalise here.
   * Teams are created sequentially to avoid interleaved directory creation.
   * Throws on any file system failure.
   */
  async createTeams(vaultPath: string, teamNames: string[]): Promise<void> {
    for (const name of teamNames) {
      await this._team.createTeam(name, vaultPath);
    }
  }

  /**
   * Adds a list of members to a given team.
   * Delegates to `TeamService.addMember()` for each entry.
   * Members are added sequentially to preserve creation order.
   * The raw display name is passed directly — `TeamService` normalises via `normalizeSlug()`.
   * On per-member failure, logs the offending email via `logger.warn` before re-throwing
   * so the command layer error message includes which member caused the abort.
   */
  async addMembersToTeam(
    vaultPath: string,
    teamName: string,
    members: Array<{ email: string; name: string; role: string; gender: string; location: string }>,
  ): Promise<void> {
    for (const member of members) {
      try {
        await this._team.addMember(
          teamName,
          member.email,
          {
            name: member.name,
            role: member.role,
            gender: member.gender,
            location: member.location,
          },
          vaultPath,
        );
      } catch (err) {
        logger.warn(
          `Failed to add member ${member.email} to ${teamName}: ${err instanceof Error ? err.message : String(err)}`,
        );
        throw err;
      }
    }
  }

  /**
   * Copies bundled Granola-formatted sample meeting notes to the vault's `inbox/` directory.
   * These real examples demonstrate the `/tmr-inbox` workflow immediately after init.
   * Throws on any file system failure.
   */
  async copySampleInboxFiles(vaultPath: string): Promise<void> {
    for (const { filename, content } of INBOX_SAMPLE_FILES) {
      await this._fs.writeFile(path.join(vaultPath, 'inbox', filename), content);
    }
  }

  /**
   * Installs default skills (tmr-inbox, tmr-project-impact, tmr-myself-config) by reading
   * their SKILL.md files directly from the bundled `docs/skills/` directory — no network
   * required. Each skill is installed independently; a failure for one does not prevent
   * the others from being attempted. Errors are logged via `logger.warn()` and swallowed —
   * skill install failures MUST NOT abort init.
   */
  async installDefaultSkill(vaultPath: string): Promise<void> {
    const registry = this._skillRegistryFactory(vaultPath);
    const BUNDLED_SKILLS = [
      { docsFolder: 'tmr-inbox', skillName: 'tmr-inbox' },
      { docsFolder: 'tmr-project-impact', skillName: 'tmr-project-impact' },
      { docsFolder: 'tmr-myself-config', skillName: 'tmr-myself-config' },
    ] as const;

    for (const { docsFolder, skillName } of BUNDLED_SKILLS) {
      try {
        const content = this._readBundledSkill(docsFolder);
        if (content === null) {
          logger.warn(`${skillName} skill install skipped: bundled file not found`);
          continue;
        }
        if (!content.trim()) {
          logger.warn(`${skillName} skill install skipped: bundled file is empty`);
          continue;
        }
        registry.installSkill(skillName, content, parseBundledVersion(content));
      } catch (err) {
        logger.warn(
          `${skillName} skill install failed: ${err instanceof Error ? err.message : String(err)}`,
        );
      }
    }
  }

  /**
   * Reads a bundled skill SKILL.md from `docs/skills/<docsFolder>/SKILL.md` relative to
   * the package root. Resolves the package root by going one level up from the compiled
   * flat bundle at `dist/<bundle>.js` (dist/ → project root).
   * Returns null on any read error.
   */
  private _readBundledSkill(docsFolder: string): string | null {
    try {
      const pkgRoot = fileURLToPath(new URL('..', import.meta.url));
      const skillPath = path.join(pkgRoot, 'docs', 'skills', docsFolder, 'SKILL.md');
      return this._readSkillFile(skillPath);
    } catch {
      return null;
    }
  }

  /**
   * Writes `config/organization.yaml` to the vault with the domain inferred from the
   * manager's email address, plus any additional validated domains collected at init.
   * The `config/` directory is guaranteed to exist after `scaffold()`.
   * Throws on any file system failure — org config is vault-critical context.
   */
  async writeOrgConfig(
    vaultPath: string,
    managerEmail: string,
    additionalDomains: string[] = [],
  ): Promise<void> {
    const inferred = (managerEmail.split('@')[1] ?? managerEmail).toLowerCase();
    const uniqueDomains = [
      inferred,
      ...additionalDomains.map((d) => d.toLowerCase()).filter((d) => d !== inferred),
    ];
    const seen = new Set<string>();
    const deduped = uniqueDomains.filter((d) => {
      if (seen.has(d)) return false;
      seen.add(d);
      return true;
    });
    const lines = deduped.map((d) => `  - ${d}`).join('\n');
    const content = `internal_domains:\n${lines}\n`;
    await this._fs.writeFile(path.join(vaultPath, 'config', 'organization.yaml'), content);
  }

  /**
   * Writes a `README.md` to the vault root from the bundled template.
   * Throws on any file system failure.
   */
  async writeReadme(vaultPath: string): Promise<void> {
    await this._fs.writeFile(path.join(vaultPath, 'README.md'), generateVaultReadme());
  }

  /**
   * Prints the post-init next-steps summary to the terminal.
   * Uses `printSuccess` for the workspace-created confirmation and
   * `printInfo` for the next-steps list (FR13) and Obsidian guidance (FR14).
   */
  printPostInitSummary(vaultPath: string, plain: boolean): void {
    printSuccess(`Workspace created at ${vaultPath}`, plain);
    printInfo(
      [
        '',
        'Next steps:',
        '  1. Open this vault in Obsidian:',
        `       macOS/Linux → run: open -a Obsidian "${vaultPath}"`,
        `       Windows     → run: start "" "obsidian://${vaultPath}"`,
        `       Or open Obsidian and navigate to: ${vaultPath}`,
        '  2. Run /tmr-myself-config in Claude Code to personalize your AI context (do this first)',
        '  3. Run /tmr-inbox in Claude Code to process your inbox meeting notes',
        '  4. Run `tmr --help` to explore all commands',
        '',
        'Skills installed:',
        '  /tmr-myself-config      — personalize AI context across your vault',
        '  /tmr-inbox              — process inbox meeting notes into structured entries',
        '  /tmr-project-impact     — detect which docs are affected when a project changes',
        '',
        'Obsidian plugins installed: obsidian-git, granola-sync, terminal, dataview',
      ].join('\n'),
      plain,
    );
  }
}

export const initService = new InitService(fileSystemService, leadershipService, teamService);
